spring.application.name=result-frontend
server.port=8082

# URLs des services backend (surchargées par variables d'environnement en Kubernetes)
sample.api.url=${SAMPLE_API_URL:http://localhost:8080}
analysis.api.url=${ANALYSIS_API_URL:http://localhost:8081}

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
