// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: labotrack.proto

// Protobuf Java Version: 3.25.3
package fr.insa.mesh.grpc;

public interface GetSampleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:labotrack.GetSampleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sample_id = 1;</code>
   * @return The sampleId.
   */
  java.lang.String getSampleId();
  /**
   * <code>string sample_id = 1;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();
}
