// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: labotrack.proto

// Protobuf Java Version: 3.25.3
package fr.insa.mesh.grpc;

public interface SampleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:labotrack.SampleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string patient_name = 2;</code>
   * @return The patientName.
   */
  java.lang.String getPatientName();
  /**
   * <code>string patient_name = 2;</code>
   * @return The bytes for patientName.
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();

  /**
   * <code>string exam_type = 3;</code>
   * @return The examType.
   */
  java.lang.String getExamType();
  /**
   * <code>string exam_type = 3;</code>
   * @return The bytes for examType.
   */
  com.google.protobuf.ByteString
      getExamTypeBytes();

  /**
   * <code>string sample_type = 4;</code>
   * @return The sampleType.
   */
  java.lang.String getSampleType();
  /**
   * <code>string sample_type = 4;</code>
   * @return The bytes for sampleType.
   */
  com.google.protobuf.ByteString
      getSampleTypeBytes();

  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
