apiVersion: v1
kind: Namespace
metadata:
  name: labotrack
  annotations:
    # Injection automatique du proxy Linkerd dans tous les pods du namespace
    linkerd.io/inject: enabled
  labels:
    app.kubernetes.io/part-of: labotrack
