// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: labotrack.proto

// Protobuf Java Version: 3.25.3
package fr.insa.mesh.grpc;

public final class Labotrack {
  private Labotrack() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labotrack_GetSampleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labotrack_GetSampleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labotrack_SampleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labotrack_SampleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labotrack_UpdateStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labotrack_UpdateStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labotrack_UpdateStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labotrack_UpdateStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017labotrack.proto\022\tlabotrack\"%\n\020GetSampl" +
      "eRequest\022\021\n\tsample_id\030\001 \001(\t\"j\n\016SampleRes" +
      "ponse\022\n\n\002id\030\001 \001(\t\022\024\n\014patient_name\030\002 \001(\t\022" +
      "\021\n\texam_type\030\003 \001(\t\022\023\n\013sample_type\030\004 \001(\t\022" +
      "\016\n\006status\030\005 \001(\t\"8\n\023UpdateStatusRequest\022\021" +
      "\n\tsample_id\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\";\n\024Upd" +
      "ateStatusResponse\022\017\n\007success\030\001 \001(\010\022\022\n\nne" +
      "w_status\030\002 \001(\t2\245\001\n\rSampleService\022C\n\tGetS" +
      "ample\022\033.labotrack.GetSampleRequest\032\031.lab" +
      "otrack.SampleResponse\022O\n\014UpdateStatus\022\036." +
      "labotrack.UpdateStatusRequest\032\037.labotrac" +
      "k.UpdateStatusResponseB\025\n\021fr.insa.mesh.g" +
      "rpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_labotrack_GetSampleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_labotrack_GetSampleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labotrack_GetSampleRequest_descriptor,
        new java.lang.String[] { "SampleId", });
    internal_static_labotrack_SampleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_labotrack_SampleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labotrack_SampleResponse_descriptor,
        new java.lang.String[] { "Id", "PatientName", "ExamType", "SampleType", "Status", });
    internal_static_labotrack_UpdateStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_labotrack_UpdateStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labotrack_UpdateStatusRequest_descriptor,
        new java.lang.String[] { "SampleId", "Status", });
    internal_static_labotrack_UpdateStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_labotrack_UpdateStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labotrack_UpdateStatusResponse_descriptor,
        new java.lang.String[] { "Success", "NewStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
