// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: labotrack.proto

// Protobuf Java Version: 3.25.3
package fr.insa.mesh.grpc;

public interface UpdateStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:labotrack.UpdateStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sample_id = 1;</code>
   * @return The sampleId.
   */
  java.lang.String getSampleId();
  /**
   * <code>string sample_id = 1;</code>
   * @return The bytes for sampleId.
   */
  com.google.protobuf.ByteString
      getSampleIdBytes();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
