// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: labotrack.proto

// Protobuf Java Version: 3.25.3
package fr.insa.mesh.grpc;

public interface UpdateStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:labotrack.UpdateStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string new_status = 2;</code>
   * @return The newStatus.
   */
  java.lang.String getNewStatus();
  /**
   * <code>string new_status = 2;</code>
   * @return The bytes for newStatus.
   */
  com.google.protobuf.ByteString
      getNewStatusBytes();
}
